version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: /var/log/weatherpi.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8
loggers:
  Adafruit_BMP:
    level: INFO
    handlers: [file]
    propagate: no
  Adafruit_I2C:
    level: INFO
    handlers: [file]
    propagate: no
  Adafruit_SSD1306:
    level: INFO
    handlers: [file]
    propagate: no
  __main__:
    level: DEBUG
    handlers: [file]
    propagate: no
root:
  level: DEBUG
  handlers: [console, file]
